const assert = require("node:assert/strict");
const { test } = require("node:test");

const {
  buildExplorerDetailTabHref,
  buildObservabilitySnapshot,
  detailTabLabel,
  normalizeDetailTab,
  DETAIL_TABS,
} = require("./observability.js");

test("exposes the consumption and observability tabs alongside the existing detail tabs", () => {
  assert.ok(DETAIL_TABS.includes("consumption"));
  assert.ok(DETAIL_TABS.includes("observability"));
  assert.equal(detailTabLabel("consumption"), "Consumo analítico");
  assert.equal(detailTabLabel("observability"), "Confiabilidade & Ação");
});

test("builds persisted explorer URLs for the consumption and observability tabs", () => {
  assert.equal(buildExplorerDetailTabHref(42, "consumption"), "/explorer?tableId=42&tab=consumption");
  assert.equal(buildExplorerDetailTabHref(42, "observability"), "/explorer?tableId=42&tab=observability");
});

test("normalizes only supported tabs", () => {
  assert.equal(normalizeDetailTab("consumption"), "consumption");
  assert.equal(normalizeDetailTab("observability"), "observability");
  assert.equal(normalizeDetailTab("not-a-tab"), null);
});

test("classifies a healthy active asset as trusted and allowed", () => {
  const snapshot = buildObservabilitySnapshot({
    canonicalAsset: {
      owner: {
        owner_name: "Ana Costa",
        owner_email: "ana@example.com",
        owner_defined: true,
      },
      classification: {
        trust_score: 94,
        governance_score: 91,
        readiness_score: 92,
      },
      evidence: {
        dq_score: 96,
        freshness_seconds: 900,
        open_incidents: 0,
        critical_open_incidents: 0,
        active_dq_violation: false,
      },
      lineage: {
        impact: {
          upstream_count: 2,
          downstream_count: 6,
          process_count: 1,
          dashboard_count: 2,
          direct_dependencies_count: 3,
          impact_level: "Médio",
        },
      },
      pipeline: {
        linked: true,
        state: "ready",
        message: null,
        table_schema: "sales",
        table_name: "orders",
        pipeline_count: 1,
        primary_pipeline: {
          latest_status_label: "Sucesso",
          last_success_at: "2026-04-13T14:00:00.000Z",
          last_execution_started_at: "2026-04-13T13:55:00.000Z",
          last_execution_finished_at: "2026-04-13T14:00:00.000Z",
          last_error: null,
        },
      },
      links: {
        explorer: "/explorer?tableId=42",
        lineage: "/explorer?tableId=42&tab=lineage",
        data_quality: "/data-quality?tableId=42",
        incidents: "/incidents/tickets?tableId=42",
        audit: "/audit?entity_type=table&entity_id=42",
        certification: "/certification?tableId=42",
        owners: "/data-owners?ownerId=8",
        privacy: "/privacy-access?tableId=42",
        datasource: "/explorer?datasourceId=1",
        database: "/explorer?datasourceId=1&databaseId=2",
        schema: "/explorer?datasourceId=1&databaseId=2&schemaId=3",
      },
      recent_events: [],
    },
    operationalContext: {
      table_id: 42,
      table_name: "orders",
      table_fqn: "warehouse.sales.orders",
      datasource_id: 1,
      datasource_name: "warehouse",
      database_id: 2,
      database_name: "sales",
      schema_id: 3,
      schema_name: "sales",
      owner_name: "Ana Costa",
      owner_defined: true,
      data_owner_id: 8,
      criticality_score: 80,
      criticality_label: "Alta",
      criticality_tone: "warning",
      dq_score: 96,
      dq_status_label: "Excelente",
      certification_status: "certified",
      certification_status_label: "Certificada",
      dictionary_complete: true,
      description_complete: true,
      tags_count: 3,
      terms_count: 2,
      open_incidents: 0,
      critical_open_incidents: 0,
      eligible_for_certification: true,
      sensitivity_level: null,
      sensitivity_label: "Não classificado",
      owner_review_due: false,
      privacy_review_due: false,
      certification_review_due: false,
      last_review_at: "2026-04-13T13:30:00.000Z",
      last_updated_at: "2026-04-13T14:00:00.000Z",
      last_sync_at: "2026-04-13T14:00:00.000Z",
      recommended_actions: ["Manter monitoramento"],
      actions: [],
      links: {
        explorer: "/explorer?tableId=42",
        lineage: "/explorer?tableId=42&tab=lineage",
        data_quality: "/data-quality?tableId=42",
        incidents: "/incidents/tickets?tableId=42",
        audit: "/audit?entity_type=table&entity_id=42",
        certification: "/certification?tableId=42",
        owners: "/data-owners?ownerId=8",
        privacy: "/privacy-access?tableId=42",
        datasource: "/explorer?datasourceId=1",
        database: "/explorer?datasourceId=1&databaseId=2",
        schema: "/explorer?datasourceId=1&databaseId=2&schemaId=3",
      },
    },
    correlationSummary: {
      table_id: 42,
      locator: {
        table_id: 42,
        datasource_id: 1,
        datasource_name: "warehouse",
        database_id: 2,
        database_name: "sales",
        schema_id: 3,
        schema_name: "sales",
        table_name: "orders",
        kind: "table",
        db_type: "postgres",
      },
      operational_context: null,
      ingestion: null,
      stability: null,
      governance_score: {
        score: 88,
        max_score: 100,
        label: "Boa",
        tone: "success",
        completed_factors: 0,
        partial_factors: 0,
        total_factors: 0,
        summary: "Estável",
        factors: [],
      },
      governance_trend: null,
      dq: {
        dq_score: 96,
        failed_rules: 0,
        freshness_seconds: 900,
        run_at: "2026-04-13T14:00:00.000Z",
        correlated_rules: [],
      },
      incident_signals: null,
      incidents: {
        open_count: 0,
        critical_open_count: 0,
        latest_open_incident_id: null,
        latest_open_incident_title: null,
        items: [],
      },
      operational_sla: null,
      incident_prefill: null,
      asset_id: 42,
      asset_name: "orders",
      qualified_name: "warehouse.sales.orders",
      schema_name: "sales",
      source_name: "warehouse",
      has_operational_failure: false,
      has_dq_degradation: false,
      has_open_incident: false,
      priority_score: 0,
      correlation_type: "Sem correlação crítica relevante",
      summary: "Nenhum sinal crítico relevante foi identificado neste momento.",
      signals: {
        combined_attention: false,
        operational_failure: false,
        stale_pipeline: false,
        open_incident: false,
        dq_below_threshold: false,
        summary: "Sem sinal crítico",
      },
    },
    tableInfo: {
      id: 42,
      schema_id: 3,
      data_owner_id: 8,
      owner: "Ana Costa",
      owner_email: "ana@example.com",
      description_source: "description",
      description_manual: "description",
      lifecycle_status: "active",
      certification_status: "certified",
      certification_criticality: "high",
      certification_badges: ["executive"],
      certification_notes: null,
      certification_submitted_by_user_id: null,
      certification_submitted_by_user_name: null,
      certification_submitted_by_user_email: null,
      certification_submitted_at: null,
      certification_decided_by_user_id: null,
      certification_decided_by_user_name: null,
      certification_decided_by_user_email: null,
      certification_decided_at: null,
      certification_review_at: null,
      certification_expires_at: null,
      owner_reviewed_by_user_id: null,
      owner_reviewed_by_user_name: null,
      owner_reviewed_by_user_email: null,
      owner_reviewed_at: null,
      sensitivity_level: null,
      has_personal_data: false,
      has_sensitive_personal_data: false,
      legal_basis: null,
      retention_policy: null,
      is_masked: false,
      external_sharing: false,
      access_scope: null,
      access_roles: null,
      privacy_notes: null,
      privacy_reviewed_by_user_name: null,
      privacy_reviewed_by_user_email: null,
      privacy_reviewed_at: null,
      created_at: "2026-04-13T10:00:00.000Z",
      updated_at: "2026-04-13T14:00:00.000Z",
      data_owner: null,
      data_contract: {
        contract_id: 7,
        version: 2,
        status: "active",
        published_at: "2026-04-12T10:00:00.000Z",
        last_validation_status: "success",
        last_validation_at: "2026-04-13T13:45:00.000Z",
        last_validation_issues: 0,
      },
    },
  });

  assert.equal(snapshot.confidenceState, "trusted");
  assert.equal(snapshot.usageDecision.state, "usage_allowed");
  assert.equal(snapshot.nextAction.label, "Manter uso monitorado");
  assert.match(snapshot.confidenceReason, /Confiável/);
});

test("marks a risky asset as blocked when operational and DQ signals are critical", () => {
  const snapshot = buildObservabilitySnapshot({
    canonicalAsset: {
      owner: {
        owner_name: null,
        owner_email: null,
        owner_defined: false,
      },
      classification: {
        trust_score: 38,
        governance_score: 35,
        readiness_score: 30,
      },
      evidence: {
        dq_score: 52,
        freshness_seconds: 90000,
        open_incidents: 2,
        critical_open_incidents: 1,
        active_dq_violation: true,
      },
      lineage: null,
      pipeline: {
        linked: true,
        state: "failure",
        message: "Falha recente",
        table_schema: "sales",
        table_name: "orders",
        pipeline_count: 1,
        primary_pipeline: {
          latest_status_label: "Falha",
          last_error: "timeout",
          last_execution_started_at: "2026-04-13T13:55:00.000Z",
          last_execution_finished_at: "2026-04-13T14:00:00.000Z",
          last_success_at: "2026-04-13T12:00:00.000Z",
        },
      },
      links: {
        explorer: "/explorer?tableId=99",
        lineage: "/explorer?tableId=99&tab=lineage",
        data_quality: "/data-quality?tableId=99",
        incidents: "/incidents/tickets?tableId=99",
        audit: "/audit?entity_type=table&entity_id=99",
        certification: "/certification?tableId=99",
        owners: "/data-owners",
        privacy: "/privacy-access?tableId=99",
        datasource: "/explorer?datasourceId=1",
        database: "/explorer?datasourceId=1&databaseId=2",
        schema: "/explorer?datasourceId=1&databaseId=2&schemaId=3",
      },
      recent_events: [],
    },
    operationalContext: {
      table_id: 99,
      table_name: "orders",
      table_fqn: "warehouse.sales.orders",
      datasource_id: 1,
      datasource_name: "warehouse",
      database_id: 2,
      database_name: "sales",
      schema_id: 3,
      schema_name: "sales",
      owner_name: null,
      owner_defined: false,
      data_owner_id: null,
      criticality_score: 90,
      criticality_label: "Crítica",
      criticality_tone: "danger",
      dq_score: 52,
      dq_status_label: "Crítico",
      certification_status: "rejected",
      certification_status_label: "Recusada",
      dictionary_complete: false,
      description_complete: false,
      tags_count: 0,
      terms_count: 0,
      open_incidents: 2,
      critical_open_incidents: 1,
      eligible_for_certification: false,
      sensitivity_level: "high",
      sensitivity_label: "Sensível",
      owner_review_due: true,
      privacy_review_due: true,
      certification_review_due: true,
      last_review_at: null,
      last_updated_at: "2026-04-13T14:00:00.000Z",
      last_sync_at: "2026-04-13T14:00:00.000Z",
      recommended_actions: ["Tratar incidente aberto"],
      actions: [],
      links: {
        explorer: "/explorer?tableId=99",
        lineage: "/explorer?tableId=99&tab=lineage",
        data_quality: "/data-quality?tableId=99",
        incidents: "/incidents/tickets?tableId=99",
        audit: "/audit?entity_type=table&entity_id=99",
        certification: "/certification?tableId=99",
        owners: "/data-owners",
        privacy: "/privacy-access?tableId=99",
        datasource: "/explorer?datasourceId=1",
        database: "/explorer?datasourceId=1&databaseId=2",
        schema: "/explorer?datasourceId=1&databaseId=2&schemaId=3",
      },
    },
    correlationSummary: {
      table_id: 99,
      locator: {
        table_id: 99,
        datasource_id: 1,
        datasource_name: "warehouse",
        database_id: 2,
        database_name: "sales",
        schema_id: 3,
        schema_name: "sales",
        table_name: "orders",
        kind: "table",
        db_type: "postgres",
      },
      operational_context: null,
      ingestion: null,
      stability: null,
      governance_score: {
        score: 18,
        max_score: 100,
        label: "Baixa",
        tone: "danger",
        completed_factors: 0,
        partial_factors: 0,
        total_factors: 0,
        summary: "Crítico",
        factors: [],
      },
      governance_trend: null,
      dq: {
        dq_score: 52,
        failed_rules: 4,
        freshness_seconds: 90000,
        run_at: "2026-04-13T14:00:00.000Z",
        correlated_rules: [],
      },
      incident_signals: null,
      incidents: {
        open_count: 2,
        critical_open_count: 1,
        latest_open_incident_id: 7,
        latest_open_incident_title: "Falha downstream",
        items: [],
      },
      operational_sla: null,
      incident_prefill: null,
      asset_id: 99,
      asset_name: "orders",
      qualified_name: "warehouse.sales.orders",
      schema_name: "sales",
      source_name: "warehouse",
      has_operational_failure: true,
      has_dq_degradation: true,
      has_open_incident: true,
      priority_score: 12,
      correlation_type: "Falha operacional + DQ degradada + incidente aberto",
      summary: "Falha operacional, DQ degradada e incidente aberto aparecem ao mesmo tempo neste ativo.",
      signals: {
        combined_attention: true,
        operational_failure: true,
        stale_pipeline: true,
        open_incident: true,
        dq_below_threshold: true,
        summary: "Crítico",
      },
    },
    tableInfo: {
      id: 99,
      schema_id: 3,
      data_owner_id: null,
      owner: null,
      owner_email: null,
      description_source: null,
      description_manual: null,
      lifecycle_status: null,
      certification_status: "rejected",
      certification_criticality: "high",
      certification_badges: [],
      certification_notes: null,
      certification_submitted_by_user_id: null,
      certification_submitted_by_user_name: null,
      certification_submitted_by_user_email: null,
      certification_submitted_at: null,
      certification_decided_by_user_id: null,
      certification_decided_by_user_name: null,
      certification_decided_by_user_email: null,
      certification_decided_at: null,
      certification_review_at: null,
      certification_expires_at: null,
      owner_reviewed_by_user_id: null,
      owner_reviewed_by_user_name: null,
      owner_reviewed_by_user_email: null,
      owner_reviewed_at: null,
      sensitivity_level: "high",
      has_personal_data: true,
      has_sensitive_personal_data: true,
      legal_basis: null,
      retention_policy: null,
      is_masked: false,
      external_sharing: false,
      access_scope: null,
      access_roles: null,
      privacy_notes: null,
      privacy_reviewed_by_user_name: null,
      privacy_reviewed_by_user_email: null,
      privacy_reviewed_at: null,
      created_at: "2026-04-13T10:00:00.000Z",
      updated_at: "2026-04-13T14:00:00.000Z",
      data_owner: null,
      data_contract: {
        contract_id: 2,
        version: 1,
        status: "draft",
        published_at: null,
        last_validation_status: "failed",
        last_validation_at: "2026-04-13T13:45:00.000Z",
        last_validation_issues: 3,
      },
    },
  });

  assert.equal(snapshot.confidenceState, "usage_blocked");
  assert.equal(snapshot.usageDecision.state, "usage_blocked");
  assert.equal(snapshot.nextAction.label, "Tratar incidente aberto");
  assert.match(snapshot.confidenceReason, /Uso bloqueado/);
});

test("falls back to insufficient evidence when there is no operational signal", () => {
  const snapshot = buildObservabilitySnapshot({
    canonicalAsset: {
      owner: {
        owner_name: null,
        owner_email: null,
        owner_defined: false,
      },
      classification: {
        trust_score: null,
        governance_score: null,
        readiness_score: null,
      },
      evidence: {
        dq_score: null,
        freshness_seconds: null,
        open_incidents: 0,
        critical_open_incidents: 0,
        active_dq_violation: false,
      },
      lineage: null,
      pipeline: null,
      links: {
        explorer: "/explorer?tableId=7",
        lineage: "/explorer?tableId=7&tab=lineage",
        data_quality: "/data-quality?tableId=7",
        incidents: "/incidents/tickets?tableId=7",
        audit: "/audit?entity_type=table&entity_id=7",
        certification: "/certification?tableId=7",
        owners: "/data-owners",
        privacy: "/privacy-access?tableId=7",
        datasource: "/explorer?datasourceId=1",
        database: "/explorer?datasourceId=1&databaseId=2",
        schema: "/explorer?datasourceId=1&databaseId=2&schemaId=3",
      },
      recent_events: [],
    },
    operationalContext: null,
    correlationSummary: null,
    tableInfo: null,
  });

  assert.equal(snapshot.confidenceState, "insufficient_evidence");
  assert.equal(snapshot.usageDecision.state, "usage_not_recommended");
  assert.match(snapshot.confidenceReason, /Sem evidência/);
});
